### ISSUE TITLE
load self-trained yolov5 model

### ISSUE THREAD

**Issue by Amanda-Barbara** [robmarkcole/yolov5-fastapi#6]
@robmarkcole  Hi, I want to load my self-trained yolov5 model and to use GPU mode, where I need to modify? thanks.

**Comment by robmarkcole** [comment]
You need to modify here https://github.com/robmarkcole/yolov5-fastapi/blob/78597d88269fe415f96a871548f2a7b5f8961477/celery_tasks/yolo.py#L9

**Comment by Amanda-Barbara** [comment]
@robmarkcole thanks.
